### ISSUE TITLE
disambiguation

### ISSUE THREAD

**Issue by PBarmby** [nearbygalaxies/nearbygalaxies.github.io#12]
Hello lovely UCSD nearby galaxies types, from the owner of a very-similarly-named github webpage!

I put a little disambiguation note on [our site](https://nearby-galaxies.github.io/disambiguation/) and perhaps you might be so kind as to do the same? Of course I know you have many better things to do and this isn't urgent. 

Cheers!

**Comment by lcjohnso** [comment]
URL added!
